# Generated by Django 5.1.4 on 2024-12-21 14:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_chapter', models.CharField(max_length=30, verbose_name='Название раздела подкатегорий')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='Ник инстаграмм')),
                ('description', models.TextField(verbose_name='Описание профиля')),
                ('reels_count', models.IntegerField(verbose_name='Кол-во рилсов')),
                ('subscribers', models.IntegerField(verbose_name='Кол-во подписчиков')),
                ('subscriptions', models.IntegerField(verbose_name='Кол-во подписок')),
                ('update_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время обновления')),
                ('categories', models.ManyToManyField(to='app.categories')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=44, verbose_name='url рилса')),
                ('likes', models.IntegerField(verbose_name='Кол-во лайков')),
                ('comments', models.IntegerField(verbose_name='Кол-во лайков')),
                ('views', models.IntegerField(verbose_name='Кол-во лайков')),
                ('description', models.TextField(verbose_name='Описание рилса')),
                ('update_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authors')),
            ],
            options={
                'db_table': 'reels',
            },
        ),
    ]
