# Generated by Django 5.1.4 on 2025-01-09 02:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MainChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'db_table': 'main_chapters',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='Ник инстаграмм')),
                ('description', models.TextField(default='', verbose_name='Описание профиля')),
                ('reels_count', models.IntegerField(default=0, verbose_name='Кол-во рилсов')),
                ('subscribers', models.IntegerField(default=0, verbose_name='Кол-во подписчиков')),
                ('subscriptions', models.IntegerField(default=0, verbose_name='Кол-во подписок')),
                ('add_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время добавления')),
                ('updated_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время обновления')),
                ('last_rell', models.IntegerField(default=0, verbose_name='Последний рилс')),
                ('new', models.BooleanField(default=True, verbose_name='Новый')),
                ('categories', models.ManyToManyField(to='app.categories')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='main_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainchapters'),
        ),
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=44, verbose_name='url на видео рилса')),
                ('likes', models.IntegerField(verbose_name='Кол-во лайков')),
                ('comments', models.IntegerField(verbose_name='Кол-во комментариев')),
                ('views', models.IntegerField(verbose_name='Кол-во просмотров')),
                ('description', models.TextField(verbose_name='Описание рилса')),
                ('published_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('updated_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время обновления')),
                ('new', models.BooleanField(default=True, verbose_name='новый')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authors')),
            ],
            options={
                'db_table': 'reels',
            },
        ),
    ]
