# Generated by Django 5.1.4 on 2024-12-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'db_table': 'main_chapters',
            },
        ),
        migrations.AlterField(
            model_name='categories',
            name='main_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mainchapters'),
        ),
    ]
