# Generated by Django 5.1.4 on 2024-12-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainchapters_alter_categories_main_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='comments',
            field=models.IntegerField(verbose_name='Кол-во комментариев'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='views',
            field=models.IntegerField(verbose_name='Кол-во просмотров'),
        ),
    ]
