# Generated by Django 5.1.4 on 2025-01-07 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reels_comments_alter_reels_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='add_stamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время добавления'),
        ),
        migrations.AddField(
            model_name='authors',
            name='last_rell',
            field=models.IntegerField(default=0, verbose_name='Последний рилс'),
        ),
    ]
