# Generated by Django 5.1.4 on 2025-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reels_shares_reels_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='shares',
            field=models.IntegerField(default=None, verbose_name='Кол-во репостов'),
        ),
    ]
