# Generated by Django 5.1.4 on 2025-01-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_authors_add_stamp_authors_last_rell'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новый'),
        ),
    ]
